services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      PGPASSWORD: "password"
      PGPORT: 5432
      PGHOST: "pgsql"

  pgsql:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ./data/dump.sql:/docker-entrypoint-initdb.d/dump.sql