name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: create docker network
        run: docker network create net
      - name: build docker container for pgsql
        run: docker build . --file Dockerfile_pgsql --tag pgsql
      - name: build docker container for app
        run: docker build . --file Dockerfile --tag app

  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
#      - name: Install Playwright Browsers
#        run: npx playwright install --with-deps
      - name: Run tests
        run: npx test
      - uses: actions/upload-artifact@v4
        if: always()
        env:
          CI: true
#          RETRIES: 1
        with:
#          name: playwright-report
#          path: playwright-report/
          retention-days: 30